### ISSUE TITLE
should use deploy_revision instead of deploy

### ISSUE THREAD

**Issue by giorgian** [kwhrtsk/chef-errbit-server#5]
The app recipe uses  `deploy`, so that the Chef::Provider::Deploy::Timestamped strategy is selected. 
This means that errbit gets redeployed at every chef run.

By switching to `deploy_revision`, errbit only gets redeployed when the revision changes.

**Comment by kwhrtsk** [comment]
Thanks for your advise.
I fixed it, and released as 1.2.0.
